// Writes basecoat.js: the part of Basecoat (https://basecoat.dev, basecoat-css@1.0.2, MIT) that the
// duet panel uses, as one CSS string. The panel must stay one self-contained file (no external domains),
// so it can't load the whole stylesheet (230 KB) from a CDN: this keeps the theme tokens, Tailwind's
// preflight and the rules for .btn .badge .card .label .input .textarea .dialog.
//
//   cd "$(mktemp -d)" && npm pack basecoat-css@1.0.2 && tar xzf basecoat-css-1.0.2.tgz
//   node scripts/basecoat-subset.mjs <that dir>/package/dist/basecoat.cdn.css
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const src = readFileSync(process.argv[2], "utf8");
const WANT = /^\.(btn|badge|card|label|dialog|textarea)\b|^\.input(\[type='text'\]|:not\(\[type\]\))|^\.field > textarea$/;

// Top-level blocks of `text`: [{ prelude, body, raw }], or statements ending in ";".
function blocks(text) {
	const out = [];
	let i = 0;
	while (i < text.length) {
		while (i < text.length && /\s/.test(text[i])) i++;
		if (i >= text.length) break;
		let j = i;
		let quote = "";
		while (j < text.length && (quote || (text[j] !== "{" && text[j] !== ";"))) {
			if (quote) {
				if (text[j] === "\\") j++;
				else if (text[j] === quote) quote = "";
			} else if (text[j] === '"' || text[j] === "'") quote = text[j];
			j++;
		}
		const prelude = text.slice(i, j).trim();
		if (text[j] === ";") {
			out.push({ prelude, raw: text.slice(i, j + 1) });
			i = j + 1;
			continue;
		}
		let depth = 0;
		let k = j;
		quote = "";
		for (; k < text.length; k++) {
			const c = text[k];
			if (quote) {
				if (c === "\\") k++;
				else if (c === quote) quote = "";
				continue;
			}
			if (c === '"' || c === "'") quote = c;
			else if (c === "{") depth++;
			else if (c === "}" && --depth === 0) break;
		}
		out.push({ prelude, body: text.slice(j + 1, k), raw: text.slice(i, k + 1) });
		i = k + 1;
	}
	return out;
}

const kept = [];
for (const b of blocks(src.replace(/^\/\*![^]*?\*\/\s*/, ""))) {
	if (b.body === undefined) kept.push(b.raw); // @layer order statements
	// @property: Tailwind's typed custom properties and their initial values (border style, rings, shadows).
	else if (/^@layer (theme|base|properties)$/.test(b.prelude) || /^@property --tw-/.test(b.prelude) || b.prelude === ":root" || b.prelude === ".dark") kept.push(b.raw);
	else if (b.prelude === "@layer components") {
		const rules = blocks(b.body).filter((r) => r.body !== undefined && r.prelude.split(",").some((s) => WANT.test(s.trim())));
		if (rules.length) kept.push(`@layer components {\n${rules.map((r) => "  " + r.raw).join("\n")}\n}`);
	}
}
// Drop the theme's data: URL icons (selects, checkboxes): the panel has none, and they look like external refs.
const css = kept
	.join("\n")
	.replace(/^\s*--(chevron-down-icon|chevron-down-icon-50|check-icon): url\([^\n]*\);\n/gm, "")
	.replace(/\n\s*\n/g, "\n");
writeFileSync(
	join(import.meta.dirname, "..", "basecoat.js"),
	`// Generated by scripts/basecoat-subset.mjs from basecoat-css@1.0.2 (dist/basecoat.cdn.css): the part the duet panel uses.\n` +
		`// Basecoat: MIT License, Copyright (c) 2025 Ronan Berder (https://basecoat.dev). Tailwind CSS (its preflight and theme): MIT License, Tailwind Labs, Inc.\n` +
		`export const BASECOAT_CSS = ${JSON.stringify(css)};\n`,
);
console.log(`basecoat.js: ${css.length} characters of CSS`);
